### PR TITLE
Fix markdown ToC

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by lex111** [comment]
[O RLY](https://github.com/lex111/awesome-ios-interview/blob/fix-toc/Resources/Russian.md#%D0%9A%D0%B0%D0%BA%D0%BE%D0%B9-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%D0%B5%D1%82%D1%81%D1%8F-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0-a-%D0%B8%D0%BB%D0%B8-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0-b)?

**Comment by dashvlas** [comment]
Yeah, really

**Comment by lex111** [comment]
@dashvlas it works for me, did I give an example, or do I not understand anything?

**Comment by dashvlas** [comment]
@lex111 I'm sorry, you've fixed it right the way it should be. Very glad for your help☺️

**Pull request merged**
